catching:
  auth:
    member-api-base-url: http://localhost:8081
    member-web-base-url: http://localhost:3000/index.html
    client-id: catch
    client-secret: secret
    web-redirect-url: http://localhost:5173/
